# Generated by Django 3.0.5 on 2021-02-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100, verbose_name='Nom vente')),
                ('id_boutique', models.IntegerField(blank=True, default=0, verbose_name="l'identifiant de boutique")),
                ('id_vente', models.IntegerField(blank=True, default=0, verbose_name="l'identifiant de mes ventes")),
                ('designation', models.CharField(blank=True, default=0, max_length=100, verbose_name='designation')),
                ('quantite', models.IntegerField(blank=True, default=0, verbose_name='quantite')),
                ('prix', models.IntegerField(blank=True, default=0, verbose_name='prix')),
                ('remise', models.IntegerField(blank=True, default=0, verbose_name='remise')),
                ('prix_unitaire_achat', models.IntegerField(verbose_name="prix unitaire d'achat, blank=True, default=0")),
                ('prix_unitaire_vente', models.IntegerField(verbose_name='prix unitaire de vente, blank=True, default=0')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé de compte cliet')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Mis à jour  du compte du vente')),
            ],
        ),
    ]
