# Generated by Django 3.0.5 on 2021-02-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fournisseur', models.CharField(max_length=100, verbose_name='Nom fournisseur')),
                ('id_fournisseur', models.IntegerField(blank=True, default=0, verbose_name="l'identifiant de mes fournisseurs")),
                ('adresse', models.TextField(blank=True, verbose_name="l'adresse de la fournisseurs")),
                ('telephone_fournisseur', models.IntegerField(blank=True, default=0, verbose_name='telephone_fournisseur')),
                ('email_fournisseur', models.EmailField(max_length=254, verbose_name='email fournisseur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé de compte cliet')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Mis à jour  du compte du fournisseur')),
            ],
        ),
    ]
