# Generated by Django 3.0.5 on 2021-02-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_boutique', models.IntegerField(blank=True, default=0, verbose_name="l'identifiant de boutique")),
                ('id_stock', models.IntegerField(blank=True, default=0, verbose_name="l'identifiant de mes stocks")),
                ('produits', models.CharField(blank=True, default=0, max_length=100, verbose_name='produits')),
                ('quantite', models.IntegerField(blank=True, default=0, verbose_name='quantite')),
                ('prix_unitaire', models.IntegerField(blank=True, default=0, verbose_name='prix unitaire ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé de compte cliet')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Mis à jour  du compte du stock')),
            ],
        ),
    ]
